# Generated by Django 2.2.5 on 2019-10-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='first name*', max_length=60)),
                ('last_name', models.CharField(default='first name*', max_length=60)),
                ('email', models.CharField(default='first name*', max_length=60)),
                ('password', models.CharField(default='password*', max_length=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
